#!/bin/bash
#
# Create a local directory to run and copy your files to local.
# Let PBS handle your output
mkdir /tmp/dyoon1234
cd /tmp/dyoon1234
cp -r /home/wellmangroup/many-agent-simulations/scpp_test/* .
script/batch_train config/config.yaml training OSSCPP_TargetMV 4

#Clean up your files
cd
# Retrieve your output
cp -r /tmp/dyoon1234/pp_data/* /home/wellmangroup/many-agent-simulations/scpp_test/pp_data
/bin/rm -rf /tmp/${PBS_JOBID}	

