#!/bin/bash
#PBS -S /bin/sh

#PBS -A wellman_flux
#PBS -q flux
#PBS -N mas-scpp_im_test
#PBS -t 9573
#PBS -o /home/wellmangroup/many-agent-simulations/scpp_test/../simulations/${PBS_ARRAYID}/out
#PBS -e /home/wellmangroup/many-agent-simulations/scpp_test/../simulations/${PBS_ARRAYID}/out
mkdir /tmp/${PBS_JOBID}; cd /tmp/${PBS_JOBID}; cp -r /home/wellmangroup/many-agent-simulations/scpp_test/* .; cp -r /home/wellmangroup/many-agent-simulations/scpp_test/../simulations/${PBS_ARRAYID} .
/tmp/${PBS_JOBID}/script/batch /tmp/${PBS_JOBID}/${PBS_ARRAYID} 20
cp -r ${PBS_ARRAYID} /home/wellmangroup/many-agent-simulations/scpp_test/../simulations; /bin/rm -rf /tmp/${PBS_JOBID}; chgrp -R wellman /home/wellmangroup/many-agent-simulations/scpp_test/../simulations/${PBS_ARRAYID}; chmod -R ug+wrx /home/wellmangroup/many-agent-simulations/scpp_test/../simulations/${PBS_ARRAYID}